#!/usr/bin/env python3
"""Derive the handbook command appendix data from CommandsExecutor registrations."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "src/main/java/client/command/CommandsExecutor.java"
OUTPUT = ROOT / "docs/handbook/commands.json"

CALL = re.compile(
    r'addCommand\((?:new String\[\]\{(?P<names>[^}]*)\}|"(?P<single>[^"]+)")'
    r'(?:,\s*(?P<rank>\d+))?,\s*(?P<cls>[A-Za-z0-9_]+)\.class\)'
)

RANK_NAMES = {
    0: "Member",
    1: "Donator",
    2: "JrGM",
    3: "GM",
    4: "SuperGM",
    5: "Developer",
    6: "Admin",
}

PREFIX = {0: "@", 1: "@", 2: "!", 3: "!", 4: "!", 5: "!", 6: "!"}

# safety -> (short label, German purpose)
PURPOSE = {
    "help": ("SAFE", "Befehlsübersicht öffnen"),
    "commands": ("SAFE", "Befehlsübersicht öffnen (Alias)"),
    "droplimit": ("SAFE", "Dropzahl und Drop-Limit der Map anzeigen"),
    "time": ("SAFE", "Aktuelle Serverzeit anzeigen"),
    "credits": ("SAFE", "Credits und Team anzeigen"),
    "uptime": ("SAFE", "Serverlaufzeit anzeigen"),
    "gacha": ("SAFE", "Belohnungen eines Gachapons anzeigen"),
    "dispose": ("STATE", "Hängende NPC- oder Skript-Interaktion beenden"),
    "changel": ("STATE", "Sprache umschalten"),
    "equiplv": ("SAFE", "Item-Level der Ausrüstung anzeigen"),
    "showrates": ("SAFE", "World- und Charakter-Raten anzeigen"),
    "charinfo": ("SAFE", "Level, Job, Slots, AP/SP, Mesos und Map anzeigen"),
    "companion": ("STATE", "Companion binden, rufen, steuern oder entfernen"),
    "training": ("SAFE", "Passende Trainingsorte vorschlagen"),
    "rates": ("SAFE", "Persönliche EXP-, Meso- und Drop-Raten anzeigen"),
    "online": ("SAFE", "Online-Spieler anzeigen"),
    "gm": ("SAFE", "Nachricht an die GMs senden"),
    "reportbug": ("SAFE", "Fehlerbericht an GMs und Serverlog senden"),
    "points": ("SAFE", "Reward- und Vote-Points anzeigen"),
    "joinevent": ("STATE", "Rückkehrort speichern und Event betreten"),
    "leaveevent": ("STATE", "Event verlassen und Rückkehrort nutzen"),
    "ranks": ("SAFE", "World-Rangliste öffnen"),
    "str": ("STATE", "AP auf STR verteilen"),
    "dex": ("STATE", "AP auf DEX verteilen"),
    "int": ("STATE", "AP auf INT verteilen"),
    "luk": ("STATE", "AP auf LUK verteilen"),
    "enableauth": ("STATE", "Login-Bypass und PIC-Cooldown zurücksetzen"),
    "toggleexp": ("STATE", "Eigenen EXP-Gewinn ein- oder ausschalten"),
    "mylawn": ("STATE", "Aktuelle Map beanspruchen oder freigeben"),
    "bosshp": ("SAFE", "HP aller Bosse der Map anzeigen"),
    "mobhp": ("SAFE", "HP aller Monster der Map anzeigen"),
    "gachalist": ("SAFE", "Gachapon-Informationsfenster öffnen"),
    "loot": ("STATE", "Eigene und Party-Drops der Map aufheben"),
    "mobskill": ("DANGER", "Mob-Skill auf alle Monster der Map anwenden"),
    "whatdropsfrom": ("SAFE", "Drops eines Monsters inklusive Chance anzeigen"),
    "whodrops": ("SAFE", "Dropper eines Items anzeigen"),
    "buffme": ("STATE", "Standard-GM-Buffs auf sich wirken"),
    "goto": ("STATE", "Zu einer vordefinierten Stadt warpen"),
    "recharge": ("STATE", "Verbrauchsgegenstände auffüllen"),
    "whereami": ("SAFE", "Map-, Portal-, NPC-, Mob- und Reactor-Daten anzeigen"),
    "hide": ("STATE", "GM-Hide aktivieren"),
    "unhide": ("STATE", "GM-Hide deaktivieren"),
    "sp": ("DANGER", "Verbleibende SP setzen"),
    "ap": ("DANGER", "Verbleibende AP setzen"),
    "empowerme": ("STATE", "Buff-Sammlung auf sich wirken"),
    "buffmap": ("STATE", "Alle Spieler der Map buffen"),
    "buff": ("STATE", "Einzelnen Skill-Buff wirken"),
    "bomb": ("DANGER", "Bomben-Monster spawnen"),
    "dc": ("DANGER", "Spieler trennen"),
    "cleardrops": ("DANGER", "Spieler-Drops der Map entfernen"),
    "clearslot": ("DANGER", "Inventarinhalte unwiderruflich löschen"),
    "clearsavelocs": ("DANGER", "Gespeicherte Warp-Orte löschen"),
    "warp": ("STATE", "Zu einer Map warpen"),
    "warphere": ("STATE", "Spieler aus beliebigem Channel herbeirufen"),
    "summon": ("STATE", "Spieler herbeirufen (Alias)"),
    "warpto": ("STATE", "Zu einem Spieler warpen"),
    "reach": ("STATE", "Zu einem Spieler warpen (Alias)"),
    "follow": ("STATE", "Einmalig zu einem Spieler warpen (Alias)"),
    "gmshop": ("STATE", "GM-Shop öffnen"),
    "heal": ("STATE", "Eigene HP und MP vollständig heilen"),
    "item": ("DANGER", "Item im Inventar erzeugen"),
    "drop": ("DANGER", "Item als Bodendrop erzeugen"),
    "level": ("DANGER", "Eigenes Level direkt setzen"),
    "levelpro": ("DANGER", "Stufenweise bis zum Ziellevel leveln"),
    "setslot": ("DANGER", "Inventarslots setzen"),
    "setstat": ("DANGER", "Alle Basis-Stats gemeinsam setzen"),
    "maxstat": ("DANGER", "Primär-Stats sowie HP und MP maximieren"),
    "maxskill": ("DANGER", "Alle verfügbaren Jobskills maximieren"),
    "resetskill": ("DANGER", "Skills zurücksetzen und SP erstatten"),
    "search": ("SAFE", "String.wz-Daten durchsuchen"),
    "jail": ("DANGER", "Spieler einsperren"),
    "unjail": ("DANGER", "Spieler aus dem Jail holen"),
    "job": ("DANGER", "Job ändern"),
    "unbug": ("STATE", "Selbst-Unbug und Map-Refresh ausführen"),
    "id": ("SAFE", "Lokale Handbuch-Dateien durchsuchen"),
    "debuff": ("DANGER", "Nahe Spieler mit einem Debuff belegen"),
    "fly": ("STATE", "Fliegen ein- oder ausschalten"),
    "spawn": ("DANGER", "Monster an eigener Position spawnen"),
    "mutemap": ("STATE", "Chat-Mute der Map umschalten"),
    "checkdmg": ("SAFE", "Stats, Buff-Werte und Basisschaden anzeigen"),
    "inmap": ("SAFE", "Spieler der aktuellen Map auflisten"),
    "reloadevents": ("OPS", "Event-Skripte neu laden"),
    "reloaddrops": ("OPS", "Drop-Daten neu laden"),
    "reloadportals": ("OPS", "Portal-Skripte neu laden"),
    "reloadmap": ("OPS", "Aktuelle Map-Instanz neu laden"),
    "reloadshops": ("OPS", "NPC- und Popup-Shops neu laden"),
    "hpmp": ("DANGER", "Aktuelle HP und MP setzen"),
    "maxhpmp": ("DANGER", "Basis-MaxHP und Basis-MaxMP setzen"),
    "music": ("STATE", "Mapmusik wechseln"),
    "monitor": ("OPS", "Paket-Logging für einen Charakter umschalten"),
    "monitors": ("SAFE", "Überwachte Charaktere anzeigen"),
    "ignore": ("OPS", "Autoban-Meldungen für einen Spieler ignorieren"),
    "ignored": ("SAFE", "Autoban-Ignore-Liste anzeigen"),
    "pos": ("SAFE", "Position und Foothold anzeigen"),
    "togglecoupon": ("OPS", "Coupon global aktivieren oder deaktivieren"),
    "togglewhitechat": ("STATE", "Weißen GM-Chat umschalten"),
    "fame": ("DANGER", "Fame absolut setzen"),
    "givenx": ("DANGER", "NX, Maple Points oder NX Prepaid vergeben"),
    "givevp": ("DANGER", "Vote Points verändern"),
    "givems": ("DANGER", "Mesos vergeben"),
    "giverp": ("DANGER", "Reward Points verändern"),
    "expeds": ("SAFE", "Laufende Boss-Expeditionen anzeigen"),
    "kill": ("DANGER", "Spieler töten"),
    "seed": ("STATE", "Henesys-PQ-Seeds an festen Positionen droppen"),
    "maxenergy": ("STATE", "Dojo-Energie maximieren"),
    "killall": ("DANGER", "Alle Monster der Map töten"),
    "notice": ("STATE", "World-weite Meldung senden"),
    "rip": ("STATE", "World-weite RIP-Meldung senden"),
    "openportal": ("STATE", "Benanntes Portal öffnen"),
    "closeportal": ("STATE", "Benanntes Portal schließen"),
    "pe": ("VPS-NO", "Rohpaket aus pe.txt ausführen"),
    "startevent": ("STATE", "Channel-Event starten"),
    "endevent": ("STATE", "Event-Eintritt schließen"),
    "startmapevent": ("STATE", "Klassisches Map-Event starten"),
    "stopmapevent": ("STATE", "Klassisches Map-Event stoppen"),
    "online2": ("SAFE", "Ausführliche Online-Liste anzeigen"),
    "ban": ("DANGER", "Account mit Begründung bannen"),
    "unban": ("DANGER", "Account-Ban aufheben"),
    "healmap": ("STATE", "HP und MP aller Spieler der Map heilen"),
    "healperson": ("STATE", "Einen Spieler vollständig heilen"),
    "hurt": ("DANGER", "Spieler auf 1 HP setzen"),
    "killmap": ("DANGER", "Alle Spieler der Map töten"),
    "night": ("STATE", "Nacht-Hintergrund an die Map senden"),
    "npc": ("STATE", "Nicht persistenten NPC spawnen"),
    "face": ("DANGER", "Gesicht ändern"),
    "hair": ("DANGER", "Frisur ändern"),
    "startquest": ("DANGER", "Quest starten"),
    "completequest": ("DANGER", "Aktive Quest erzwingend abschließen"),
    "resetquest": ("DANGER", "Abgeschlossene Quest zurücksetzen"),
    "timer": ("STATE", "Client-Uhr eines Spielers setzen oder entfernen"),
    "timermap": ("STATE", "Client-Uhr der Map setzen oder entfernen"),
    "timerall": ("STATE", "World-weite Client-Uhr setzen oder entfernen"),
    "warpmap": ("DANGER", "Alle Charaktere der Map warpen"),
    "warparea": ("DANGER", "Alle Spieler im Nahbereich warpen"),
    "servermessage": ("OPS", "Scrollende Servermeldung setzen oder löschen"),
    "proitem": ("DANGER", "Equip mit eigenen Werten erzeugen"),
    "seteqstat": ("DANGER", "Stats aller Equips im Inventar überschreiben"),
    "exprate": ("OPS", "World-EXP-Rate setzen"),
    "mesorate": ("OPS", "World-Meso-Rate setzen"),
    "droprate": ("OPS", "World-Drop-Rate setzen"),
    "bossdroprate": ("OPS", "World-Bossdrop-Rate setzen"),
    "questrate": ("OPS", "World-Quest-Rate setzen"),
    "travelrate": ("OPS", "World-Reise-Rate setzen"),
    "charslots": ("DANGER", "Charakterslots des Accounts setzen"),
    "storageslots": ("DANGER", "Lager-Slots erhöhen"),
    "fishrate": ("OPS", "Fisch-Rate setzen"),
    "rate": ("OPS", "World-Raten anzeigen oder setzen"),
    "itemvac": ("STATE", "Map-Drops nach normalen Regeln aufheben"),
    "forcevac": ("DANGER", "Map-Drops ohne Ownerprüfung einsammeln"),
    "zakum": ("DANGER", "Zakum spawnen"),
    "horntail": ("DANGER", "Horntail spawnen"),
    "pinkbean": ("DANGER", "Pink Bean spawnen"),
    "pap": ("DANGER", "Papulatus spawnen"),
    "pianus": ("DANGER", "Pianus spawnen"),
    "cake": ("DANGER", "Giant Cake spawnen"),
    "playernpc": ("DANGER", "Player-NPC eines Online-Spielers erzeugen"),
    "playernpcremove": ("DANGER", "Player-NPC entfernen"),
    "pnpc": ("DANGER", "NPC persistent in allen Channels spawnen"),
    "pnpcremove": ("DANGER", "Persistente NPCs entfernen"),
    "pmob": ("DANGER", "Monster persistent platzieren"),
    "pmobremove": ("DANGER", "Persistente Monster entfernen"),
    "debug": ("VPS-NO", "Debugausgaben erzeugen"),
    "set": ("VPS-NO", "Globale Debugwerte setzen"),
    "showpackets": ("VPS-NO", "Paketausgabe in der Konsole umschalten"),
    "showmovelife": ("VPS-NO", "Move-Life-Diagnose umschalten"),
    "showsessions": ("OPS", "Session-Trace ausgeben"),
    "iplist": ("OPS", "Charakter- und IP-Zuordnung anzeigen"),
    "setgmlevel": ("DANGER", "GM-Rang eines Online-Spielers ändern"),
    "warpworld": ("OPS", "World wechseln"),
    "saveall": ("OPS", "Alle Online-Charaktere speichern"),
    "dcall": ("DANGER", "Alle Nicht-GMs trennen"),
    "mapplayers": ("SAFE", "Detailinformationen der Map anzeigen"),
    "getacc": ("OPS", "Accountnamen eines Spielers anzeigen"),
    "shutdown": ("OPS", "Server herunterfahren"),
    "clearquestcache": ("OPS", "Gesamten Quest-Cache leeren"),
    "clearquest": ("OPS", "Quest-Cache einer Quest leeren"),
    "supplyratecoupon": ("OPS", "Cash-Shop-Ratecoupons umschalten"),
    "spawnallpnpcs": ("DANGER", "Player-NPCs für alle Spieler erzeugen"),
    "eraseallpnpcs": ("DANGER", "Alle Player-NPCs entfernen"),
    "addchannel": ("VPS-NO", "Channel zur Laufzeit hinzufügen"),
    "addworld": ("VPS-NO", "World zur Laufzeit hinzufügen"),
    "removechannel": ("VPS-NO", "Channel zur Laufzeit entfernen"),
    "removeworld": ("VPS-NO", "Letzte World zur Laufzeit entfernen"),
    "devtest": ("VPS-NO", "devtest.js ausführen"),
}

SYNTAX = {
    "gacha": "@gacha <Ort>",
    "changel": "@changel <0|1|2>",
    "companion": "@companion <bind|unbind|spawn|dismiss|mode|loot|equip|status> [Argumente]",
    "training": "@training [Level]",
    "gm": "@gm <Nachricht>",
    "reportbug": "@reportbug <Nachricht>",
    "points": "@points [rp|vp|all]",
    "str": "@str [Anzahl]",
    "dex": "@dex [Anzahl]",
    "int": "@int [Anzahl]",
    "luk": "@luk [Anzahl]",
    "whatdropsfrom": "@whatdropsfrom <Monstername>",
    "whodrops": "@whodrops <Itemname>",
    "goto": "@goto [Gebietsname]",
    "sp": "!sp <neueSP> | !sp <Spieler> <neueSP>",
    "ap": "!ap <neueAP> | !ap <Spieler> <neueAP>",
    "buff": "!buff <Skill-ID>",
    "bomb": "!bomb [Spieler]",
    "dc": "!dc <Spieler>",
    "clearslot": "!clearslot <all|equip|use|setup|etc|cash>",
    "clearsavelocs": "!clearsavelocs <Spieler>",
    "warp": "!warp <Map-ID>",
    "warphere": "!warphere <Spieler>",
    "summon": "!summon <Spieler>",
    "warpto": "!warpto <Spieler>",
    "reach": "!reach <Spieler>",
    "follow": "!follow <Spieler>",
    "item": "!item <Item-ID> [Menge]",
    "drop": "!drop <Item-ID> [Menge]",
    "level": "!level <Level>",
    "levelpro": "!levelpro <Level>",
    "setslot": "!setslot <Anzahl>",
    "setstat": "!setstat <Wert>",
    "search": "!search <MAP|QUEST|NPC|ITEM|MOB|MONSTER|SKILL> <Name>",
    "jail": "!jail <Spieler> [Minuten]",
    "unjail": "!unjail <Spieler>",
    "job": "!job <Job-ID> | !job <Spieler> <Job-ID>",
    "id": "!id <map|etc|npc|use|weapon> <Suchtext>",
    "debuff": "!debuff <SLOW|SEDUCE|ZOMBIFY|CONFUSE|STUN|POISON|SEAL|DARKNESS|WEAKEN|CURSE>",
    "fly": "!fly <on|off>",
    "spawn": "!spawn <Mob-ID> [Menge]",
    "checkdmg": "!checkdmg <Spieler>",
    "hpmp": "!hpmp <Wert> | !hpmp <Spieler> <Wert>",
    "maxhpmp": "!maxhpmp <Wert> | !maxhpmp <Spieler> <Wert>",
    "music": "!music [Songname]",
    "monitor": "!monitor <Spieler>",
    "ignore": "!ignore <Spieler>",
    "togglecoupon": "!togglecoupon <Item-ID>",
    "fame": "!fame <Spieler> <Wert>",
    "givenx": "!givenx <nx|mp|np> [Spieler] <Wert>",
    "givevp": "!givevp <Spieler> <Änderung>",
    "givems": "!givems [Spieler] <Wert|max|min>",
    "giverp": "!giverp <Spieler> <Änderung>",
    "kill": "!kill <Spieler>",
    "notice": "!notice <Nachricht>",
    "rip": "!rip <Text…>",
    "openportal": "!openportal <Portalname>",
    "closeportal": "!closeportal <Portalname>",
    "startevent": "!startevent [Limit] [zweites Argument]",
    "ban": "!ban <Spieler> <Grund…>",
    "unban": "!unban <Spieler>",
    "healperson": "!healperson <Spieler>",
    "hurt": "!hurt <Spieler>",
    "npc": "!npc <NPC-ID>",
    "face": "!face <Face-ID> | !face <Spieler> <Face-ID>",
    "hair": "!hair <Hair-ID> | !hair <Spieler> <Hair-ID>",
    "startquest": "!startquest <Quest-ID>",
    "completequest": "!completequest <Quest-ID>",
    "resetquest": "!resetquest <Quest-ID>",
    "timer": "!timer <Spieler> <Sekunden|remove>",
    "timermap": "!timermap <Sekunden|remove>",
    "timerall": "!timerall <Sekunden|remove>",
    "warpmap": "!warpmap <Map-ID>",
    "warparea": "!warparea <Map-ID>",
    "servermessage": "!servermessage <Text>",
    "proitem": "!proitem <Item-ID> <Statwert> [Speed/Jump-Wert]",
    "seteqstat": "!seteqstat <Statwert> [Speed/Jump-Wert]",
    "exprate": "!exprate <Rate>",
    "mesorate": "!mesorate <Rate>",
    "droprate": "!droprate <Rate>",
    "bossdroprate": "!bossdroprate <Rate>",
    "questrate": "!questrate <Rate>",
    "travelrate": "!travelrate <Rate>",
    "charslots": "!charslots <Ziel>",
    "storageslots": "!storageslots <Ziel>",
    "fishrate": "!fishrate <Rate>",
    "rate": "!rate [exp|meso|drop|boss|quest|travel|fish] [Wert]",
    "cake": "!cake [HP]",
    "playernpc": "!playernpc <Online-Spieler>",
    "playernpcremove": "!playernpcremove <Online-Spieler>",
    "pnpc": "!pnpc <NPC-ID>",
    "pnpcremove": "!pnpcremove [NPC-ID]",
    "pmob": "!pmob <Mob-ID> [Respawnzeit]",
    "pmobremove": "!pmobremove [Mob-ID]",
    "mobskill": "!mobskill <MobSkill-ID> <Level>",
    "debug": "!debug <Typ>",
    "set": "!set [Integer…]",
    "setgmlevel": "!setgmlevel <Spieler> <0..6>",
    "warpworld": "!warpworld <World-ID>",
    "getacc": "!getacc <Spieler>",
    "shutdown": "!shutdown <Minuten|NOW>",
    "clearquest": "!clearquest <Quest-ID>",
    "supplyratecoupon": "!supplyratecoupon <yes|no>",
    "addchannel": "!addchannel <World-ID>",
    "removechannel": "!removechannel <World-ID>",
}

NOTES = {
    "follow": "Kein dauerhaftes Folgen; Alias für einmaliges Warpto.",
    "rip": "Verwirft immer das erste Textwort der Eingabe.",
    "startevent": "Ein einzelner Limit-Parameter wird ignoriert; erst ab zwei Parametern greift das Limit.",
    "dcall": "Trennt ausschließlich Nicht-GMs, entgegen der Kurzbeschreibung.",
    "removeworld": "Entfernt immer die letzte World; keine World-ID wählbar.",
    "supplyratecoupon": "Nur exakt 'no' deaktiviert; jeder andere Text aktiviert.",
    "fame": "Setzt Fame absolut, obwohl der Parameter gainfame heißt.",
    "setslot": "Die Ingame-Hilfe nennt fälschlich <newlevel>; es werden Inventarslots gesetzt.",
    "job": "Bei zwei Parametern gilt <Spieler> <Job-ID>, nicht die Reihenfolge der Hilfemeldung.",
    "item": "Bei Pets ist das zweite Argument eine Laufzeit in Tagen, keine Menge.",
    "drop": "Bei Pets ist das zweite Argument eine Laufzeit in Tagen, keine Menge.",
    "reportbug": "Fehlermeldung nennt @bug; registriert ist ausschließlich reportbug.",
    "clearsavelocs": "Ohne Spielerangabe folgt ein Indexfehler; immer einen Namen angeben.",
    "debug": "Der Typ packet ist funktionslos; unbekannte Typen erzeugen keine Meldung.",
    "checkdmg": "Ohne Argument bricht der Befehlspfad ab; immer einen Spieler angeben.",
    "healperson": "Ohne Argument bricht der Befehlspfad ab; immer einen Spieler angeben.",
    "hurt": "Ohne Argument bricht der Befehlspfad ab; immer einen Spieler angeben.",
    "points": "Unbekannte Zusatzargumente zeigen beiden Punktarten.",
}

ALIAS_OF = {
    "commands": "help",
    "summon": "warphere",
    "reach": "warpto",
    "follow": "warpto",
}


def main() -> None:
    text = SOURCE.read_text(encoding="utf-8")
    seen: dict[str, dict] = {}
    order: list[str] = []

    for match in CALL.finditer(text):
        if match.group("names"):
            names = [part.strip().strip('"') for part in match.group("names").split(",") if part.strip()]
        else:
            names = [match.group("single")]
        rank = int(match.group("rank") or 0)
        cls = match.group("cls")
        for index, name in enumerate(names):
            if name in seen:
                continue
            safety, purpose = PURPOSE.get(name, ("STATE", "Befehl der Rangstufe " + RANK_NAMES[rank]))
            seen[name] = {
                "name": name,
                "rank": rank,
                "rankName": RANK_NAMES[rank],
                "prefix": PREFIX[rank],
                "syntax": SYNTAX.get(name, PREFIX[rank] + name),
                "purpose": purpose,
                "safety": safety,
                "implementation": cls,
                "aliasOf": ALIAS_OF.get(name),
                "primaryName": None if index == 0 else names[0],
                "notes": NOTES.get(name),
            }
            order.append(name)

    commands = [seen[name] for name in order]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps({"commands": commands}, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    counts: dict[int, int] = {}
    for name in order:
        counts[seen[name]["rank"]] = counts.get(seen[name]["rank"], 0) + 1
    print(f"commands: {len(commands)}")
    for rank in sorted(counts):
        print(f"  rank {rank} {RANK_NAMES[rank]}: {counts[rank]}")


if __name__ == "__main__":
    main()
